#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL DUNITER
#=================================================
ynh_script_progression "Installation of Debian package of Duniter…"

ynh_setup_source --dest_dir="$install_dir"
ynh_hide_warnings dpkg -i "$install_dir/duniter-server.deb"
ynh_safe_rm "$install_dir/duniter-server.deb"

#=================================================
# CREATE DATA DIRECTORY
#=================================================
ynh_script_progression "Configuring a data directory…"

chmod -R o-rwx "$data_dir"
chown -R $app:www-data "$data_dir"

#=================================================
# CONFIGURE DUNITER
#=================================================
ynh_script_progression "Configure Duniter…"

CONFIGURE_DUNITER

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service…"

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="Web administration accessible"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
