#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)
port=$(ynh_app_setting_get $app port)

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND REMOVE APPLICATION / DEBIAN PACKAGE
#=================================================

remove_duniter

#=================================================
# Remove data and conf
#=================================================

ynh_secure_remove /root/.conf/duniter

#=================================================
# Remove Duniter service to YunoHost monitoring
#=================================================

yunohost service remove $app

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	echo "Close port $port" >&2
	yunohost firewall disallow TCP $port 2>&1
fi
