#!/bin/bash

#set -e

# Remove uCoin node daemon
pm2 delete ucoin

# Remove uCoin node
sudo npm remove ucoin

# Remove uCoin service to YunoHost monitoring
sudo yunohost service remove ucoin

# I can't remove thoses packages which could be used by other apps
#sudo npm remove pm2
#sudo apt -y -qq remove nodejs npm

# Close opened port
sudo yunohost firewall disallow TCP $port
