#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source app helpers
source /usr/share/yunohost/helpers

# Retrive arguments
app=$YNH_APP_INSTANCE_NAME
arch=$(ynh_app_setting_get "$app" arch)
version=$(cat ../conf/upstream_version)

# Stop duniter daemon
sudo $app stop

# Remove Duniter package
sudo dpkg -r duniter

# Retrive Duniter package and install it
if [ $arch == "x64" ]; then #|| $arch == "armv7l" ]
	wget -nc --quiet https://github.com/duniter/duniter/releases/download/$version/duniter-$version-linux-$arch.deb -P /tmp
else
	ynh_die "$arch is not currently supported." 2
fi
sudo dpkg -i /tmp/duniter-$version-linux-$arch.deb
#sudo rm -f /tmp/duniter-$version-linux-$arch.deb

# Start duniter daemon
sudo $app start
