#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source app helpers and functions
source /usr/share/yunohost/helpers
source functions.sh

# Retrive arguments
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
port=$(ynh_app_setting_get "$app" port)
arch=$(ynh_app_setting_get "$app" arch)
admin=$(ynh_app_setting_get "$app" admin)

# CREATE DEDICATED USER
ynh_script_progression --message="Making sure dedicated system user exists..."

# Create a dedicated user (if not existing)
ynh_system_user_create --username=$app

REMOVE_DUNITER
INSTALL_DUNITER_DEBIAN_PACKAGE
INSTALL_SYSTEMD
CONFIGURE_DUNITER

# Start duniter service
systemctl start duniter

CONFIG_PERMISSIONS
CONFIG_NGINX

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
